### ISSUE TITLE
WattmanGtk available on Aur for Manjaro, Archlinux et derivated users

### ISSUE THREAD

**Issue by olielvewen** [BoukeHaarsma23/WattmanGTK#31]
Hi,

I've discovered Monday your software on Phoronix and I've shared the news, firstly on my Google+ Page and yesterday, on my Blog (https://linuxevolution.wordpress.com/) with a blog entry, specifying that this project was not packaged for any distribution. Designing another article about GKraken, I've checked and have seen that he was already available on AUR [(https://aur.archlinux.org/packages/wattman-gtk-git/] Then, Manjaro, Archlinux and derivated users can today install it and test it and used it. You can modified your Readme now

Here the command line for install it :+1: `yaourt -S wattman-gtk-git`

Thanks a lot for your great work.

**Comment by BoukeHaarsma23** [comment]
Just to let you know in #16 also a [PKGBUILD](https://gist.github.com/BoukeHaarsma23/8c6d0b519615e5dc59a9a1e01cada758) is posted. Could you please update it? Since the current one you posted will not work

**Comment by pyamsoft** [comment]
Hi, I have updated the PKGBUILD on the AUR.

Since the project is moving so quickly, I will remove myself from maintenance of the PKGBUILD at the request of the project creator.

The PKGBUILD is orphaned and is free to adopt by anyone who is willing.

https://aur.archlinux.org/packages/wattman-gtk-git/

**Comment by BoukeHaarsma23** [comment]
Thank you @pyamsoft for your work. Greatly appreciated!
